local nnoremap = require("mattszczp.remap").nnoremap
local telescope = require("telescope.builtin")
--netrw
nnoremap("<leader>pv", "<cmd>Ex<CR>")

--Telescope
nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ff", function ()
    telescope.find_files()
end)
nnoremap("<leader>fg", function ()
    telescope.live_grep()
end)
nnoremap("<leader>fb", function ()
    telescope.buffers()
end)
nnoremap("<leader>fh", function ()
    telescope.help_tags()
end)

-- Debugging
nnoremap("<F5>", function ()
    require("dap").continue()
end)
nnoremap("<F10>", function ()
    require("dap").step_over()
end)
nnoremap("<F11>", function ()
    require("dap").step_into()
end)
nnoremap("<F12>", function ()
    require("dap").step_out()
end)
nnoremap("<leader>b", function ()
    require("dap").toggle_breakpoint()
end)
nnoremap("<leader>B", function ()
    require("dap").set_breakpoint(vim.fn.input('Breakpoint condition: '))
end)
nnoremap("<leader>lp", function()
    require("dap").set_breakpoint(nil, nil, vim.fn.input('Log point message: '))
end)
nnoremap("<leader>dr", function()
    require("dap").repl.open()
end)
