return require("packer").startup(function()
    use("wbthomason/packer.nvim")
    use("junegunn/fzf", { run = "fzf#install()" })
    use("junegunn/fzf.vim")
    use("tpope/vim-fugitive")
    use("preservim/nerdtree")
    use("fatih/vim-go", { run = ":GoUpdateBinaries" })
--CMP & LSP
    use("hrsh7th/nvim-cmp")
    use("hrsh7th/cmp-nvim-lsp")
    use("hrsh7th/cmp-buffer")
    use("tzachar/cmp-tabnine", { run = "./install.sh" })
    use("nvim-lua/lsp_extensions.nvim")
    use("hrsh7th/cmp-path")
    use("hrsh7th/cmp-cmdline")
    use("hrsh7th/vim-vsnip")
    use("hrsh7th/cmp-vsnip")
--CMP & LSP END
    use("gruvbox-community/gruvbox")
    use("neovim/nvim-lspconfig")
    use("williamboman/nvim-lsp-installer")
    use("nvim-treesitter/nvim-treesitter", { run = ":TSUpdate"})
    use("onsails/lspkind.nvim")
end)
