---
- name: Install Poetry
  pip:
    name: poetry
  tags:
    - work
    - python

- name: Install Homebrew

- name: Install Cloud CLIs
- name: Install K8s tools
- name: Install GVM
- name: Install NVM
- name: Install IaC tools

